import type { Metadata } from 'next';
import './globals.css';
// import { usePathname } from 'next/navigation';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // console.log(Layout);

  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
